# Generated by Django 3.2.3 on 2023-09-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('User', 'User')], default=('User', 'User'), max_length=200)),
            ],
        ),
    ]
