# Generated by Django 3.2.3 on 2023-09-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='StudentPayment',
        ),
    ]
