# Generated by Django 3.2.3 on 2023-12-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_message_studentpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='enddate',
            field=models.DateTimeField(null=True),
        ),
    ]
