# Generated by Django 3.2.3 on 2023-12-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_alter_studentcourse_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
