# Generated by Django 3.2.3 on 2023-12-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_alter_student_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='enddate',
            field=models.DateField(null=True),
        ),
    ]
