# Generated by Django 3.2.3 on 2023-12-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_auto_20231201_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
